// import data
const fake = {
  NameStudyPrograms: "NGÀNH CÔNG NGHỆ THÔNG TIN",
  Key: 12,
  IDFaculty: 53,
  DataCourse: [
    {
      BlockKnowledge: "Kiến thức đại cương",
      STC: 37,
      value: [
        {
          STT: 1,
          MHP: "SSH1205",
          TENHP: "Tư tưởng Hồ Chí Minh",
          STC: 2,
          LT_BT: 2,
          TH: 0,
          DAMH_BTL: 0,
          KLTN_DATN_TT: 0,
          GIO_TH: 30,
          MHPKQ: "",
          HK: 4,
        },
        {
          STT: 1,
          MHP: "SSH1201",
          TENHP: "Triết học Mác - Lênin",
          STC: 3,
          LT_BT: 3,
          TH: 0,
          DAMH_BTL: 0,
          KLTN_DATN_TT: 0,
          GIO_TH: 45,
          MHPKQ: "IT1208",
          HK: 4,
        },
      ],
    },
    {
      BlockKnowledge: "Kiến thức cơ sở ngành",
      STC: 27,
      value: [
        {
          STT: 18,
          MHP: "IT2201",
          TENHP: "Cơ sở lập trình với C",
          STC: 3,
          LT_BT: 2,
          TH: 1,
          DAMH_BTL: 0,
          KLTN_DATN_TT: 0,
          GIO_TH: 75,
          MHPKQ: "",
          HK: 2,
        },
        {
          STT: 2,
          MHP: "IT2204",
          TENHP: "Hệ thống thông tin quản lý",
          STC: 3,
          LT_BT: 2,
          TH: 1,
          DAMH_BTL: 0,
          KLTN_DATN_TT: 0,
          GIO_TH: 75,
          MHPKQ: "IT1208",
          HK: 4,
        },
      ],
    },
  ],
};
